### ISSUE TITLE
Crash in pcs due to gperf modifying environ variable

### ISSUE THREAD

**Issue by rohsaini** [gperftools/gperftools#1044]
My application is using both gperf and pcs. gperf gets activated on these below environment variables. As per gperf behavior, gperf modifies 1st character of HEAPPROFILE (current ascii value + 128 ) in order to identify parent-child relationship amonst processes. HEAPPROFILE gets modified to ¯opt/pw/runtime/users/debug/hng_heap_profile from /opt/pw/runtime/users/debug/hng_heap_profile

This is causing crash in external.py as it tries to log all the environment variables and crashes due to non-ascii character found in HEAPPROFILE.
Can gperf manage parent-child relationship without modifying the the HEAPPROFILE env variable.

export HEAPPROFILE=/opt/pw/runtime/users/debug/hng_heap_profile
export HEAP_PROFILE_ALLOCATION_INTERVAL=0
export HEAP_PROFILE_INUSE_INTERVAL=0

Refer gperf--
https://github.com/gperftools/gperftools/blob/f47a52ce85c3d8d559aaae7b7a426c359fbca225/src/base/sysinfo.cc

Function: GetUniquePathFromEnv

Refer pcsd external.py --
Crash in function run of class CommandRunner.
https://github.com/ClusterLabs/pcs/blob/master/pcs/lib/external.py

Backtrace:

2018-09-12T05:51:57.473302+01:00 rohit-hng1 UniTaskC: ........Traceback (most recent call last):
2018-09-12T05:51:57.473716+01:00 rohit-hng1 UniTaskC: File "/sbin/pcs", line 9, in 
2018-09-12T05:51:57.474022+01:00 rohit-hng1 UniTaskC: load_entry_point('pcs==0.9.158', 'console_scripts', 'pcs')()
2018-09-12T05:51:57.474187+01:00 rohit-hng1 UniTaskC: File "/usr/lib/python2.7/site-packages/pcs/app.py", line 191, in main
2018-09-12T05:51:57.475963+01:00 rohit-hng1 UniTaskC: cmd_mapcommand
2018-09-12T05:51:57.476214+01:00 rohit-hng1 UniTaskC: File "/usr/lib/python2.7/site-packages/pcs/cluster.py", line 89, in cluster_cmd
2018-09-12T05:51:57.477303+01:00 rohit-hng1 UniTaskC: cluster_setup([utils.pcs_options["--name"]] + argv)
2018-09-12T05:51:57.477559+01:00 rohit-hng1 UniTaskC: File "/usr/lib/python2.7/site-packages/pcs/cluster.py", line 312, in cluster_setup
2018-09-12T05:51:57.477749+01:00 rohit-hng1 UniTaskC: is_rhel6 = utils.is_rhel6()
2018-09-12T05:51:57.477940+01:00 rohit-hng1 UniTaskC: File "/usr/lib/python2.7/site-packages/pcs/utils.py", line 2191, in is_rhel6
2018-09-12T05:51:57.479232+01:00 rohit-hng1 UniTaskC: return is_cman_cluster()
2018-09-12T05:51:57.479467+01:00 rohit-hng1 UniTaskC: File "/usr/lib/python2.7/site-packages/pcs/common/tools.py", line 20, in wrapper
2018-09-12T05:51:57.495395+01:00 rohit-hng1 UniTaskC: cache["value"] = func()
2018-09-12T05:51:57.495677+01:00 rohit-hng1 UniTaskC: File "/usr/lib/python2.7/site-packages/pcs/utils.py", line 2195, in is_cman_cluster
2018-09-12T05:51:57.495861+01:00 rohit-hng1 UniTaskC: return lib_is_cman_cluster(cmd_runner())
2018-09-12T05:51:57.496012+01:00 rohit-hng1 UniTaskC: File "/usr/lib/python2.7/site-packages/pcs/lib/external.py", line 336, in is_cman_cluster
2018-09-12T05:51:57.496158+01:00 rohit-hng1 UniTaskC: "-v"
2018-09-12T05:51:57.496305+01:00 rohit-hng1 UniTaskC: File "/usr/lib/python2.7/site-packages/pcs/lib/external.py", line 395, in run
2018-09-12T05:51:57.496536+01:00 rohit-hng1 UniTaskC: for key, val in sorted(env_vars.items())
2018-09-12T05:51:57.496722+01:00 rohit-hng1 UniTaskC: UnicodeDecodeError: 'ascii' codec can't decode byte 0xaf in position 0: ordinal not in range(128)
2018-09-12T05:51:57.894707+01:00 rohit-hng1 UniTaskC: ....Starting Cluster...
2018-09-12T05:51:57.895124+01:00 rohit-hng1 UniTaskC: Traceback (most recent call last):
2018-09-12T05:51:57.895423+01:00 rohit-hng1 UniTaskC: File "/sbin/pcs", line 9, in 
2018-09-12T05:51:57.895693+01:00 rohit-hng1 UniTaskC: load_entry_point('pcs==0.9.158', 'console_scripts', 'pcs')()
2018-09-12T05:51:57.895988+01:00 rohit-hng1 UniTaskC: File "/usr/lib/python2.7/site-packages/pcs/app.py", line 191, in main
2018-09-12T05:51:57.896235+01:00 rohit-hng1 UniTaskC: cmd_mapcommand
2018-09-12T05:51:57.896499+01:00 rohit-hng1 UniTaskC: File "/usr/lib/python2.7/site-packages/pcs/cluster.py", line 114, in cluster_cmd
2018-09-12T05:51:57.896756+01:00 rohit-hng1 UniTaskC: start_cluster(argv)
2018-09-12T05:51:57.897001+01:00 rohit-hng1 UniTaskC: File "/usr/lib/python2.7/site-packages/pcs/cluster.py", line 1000, in start_cluster
2018-09-12T05:51:57.897885+01:00 rohit-hng1 UniTaskC: if utils.is_cman_cluster():
2018-09-12T05:51:57.898186+01:00 rohit-hng1 UniTaskC: File "/usr/lib/python2.7/site-packages/pcs/common/tools.py", line 20, in wrapper
2018-09-12T05:51:57.898463+01:00 rohit-hng1 UniTaskC: cache["value"] = func()
2018-09-12T05:51:57.898712+01:00 rohit-hng1 UniTaskC: File "/usr/lib/python2.7/site-packages/pcs/utils.py", line 2195, in is_cman_cluster
2018-09-12T05:51:57.898954+01:00 rohit-hng1 UniTaskC: return lib_is_cman_cluster(cmd_runner())
2018-09-12T05:51:57.899213+01:00 rohit-hng1 UniTaskC: File "/usr/lib/python2.7/site-packages/pcs/lib/external.py", line 336, in is_cman_cluster
2018-09-12T05:51:57.899480+01:00 rohit-hng1 UniTaskC: "-v"
2018-09-12T05:51:57.899729+01:00 rohit-hng1 UniTaskC: File "/usr/lib/python2.7/site-packages/pcs/lib/external.py", line 395, in run
2018-09-12T05:51:57.899976+01:00 rohit-hng1 UniTaskC: for key, val in sorted(env_vars.items())
2018-09-12T05:51:57.900252+01:00 rohit-hng1 UniTaskC: UnicodeDecodeError: 'ascii' codec can't decode byte 0xaf in position 0: ordinal not in range(128)
2018-09-12T05:51:59.773509+01:00 rohit-hng1 UniTaskC: Waiting for pacemaker to start1...cpuset.sh: moved 146 tasks among 343

**Comment by alk** [comment]
Thanks for filing this issue. Yes ideally we'd do something about this. But note that _anybody_ can set non-ascii environment variable values. So it is your code that gets confused by non-ascii values that needs to be fixed regardless.

**Comment by alk** [comment]
I think it is time for us to stop doing this "set bit 7" thingy. But your python stuff failing on arbitrary ascii bytes trying to dump environment variable is the problem that needs fixing anyways.

**Comment by alk** [comment]
BTW, I think I marked this "completed" by mistake. But lets use #1603 as the main ticket for this.
