### ISSUE TITLE
Google protobuf triggers TCMalloc deadlock

### ISSUE THREAD

**Issue by MR-workaholic** [gperftools/gperftools#1126]
- I have a multi-threaded RPC program that causes TCMalloc to deadlock when certain threads perform work related to protobuf.
- This deadlock occurs after the program has been running for a while.
- Stack trace of same threads:
```
#0  0x0000000001215d76 in sys_futex (v3=0, a2=0x0, t=0x7f5a4f9b65d0, v=<optimized out>, o=128, a=0x2904380 <tcmalloc::Static::central_cache_+4864>) at ./src/base/linux_syscall_support.h:2485
2485	./src/base/linux_syscall_support.h: No such file or directory.
(gdb) bt
#0  0x0000000001215d76 in sys_futex (v3=0, a2=0x0, t=0x7f5a4f9b65d0, v=<optimized out>, o=128, a=0x2904380 <tcmalloc::Static::central_cache_+4864>) at ./src/base/linux_syscall_support.h:2485
#1  base::internal::SpinLockDelay (w=0x2904380 <tcmalloc::Static::central_cache_+4864>, value=2, loop=<optimized out>) at ./src/base/spinlock_linux-inl.h:84
#2  0x0000000001215c56 in SpinLock::SlowLock (this=0x2904380 <tcmalloc::Static::central_cache_+4864>) at src/base/spinlock.cc:119
#3  0x000000000120c841 in SpinLock::Lock (this=0x2904380 <tcmalloc::Static::central_cache_+4864>) at src/base/spinlock.h:71
#4  tcmalloc::CentralFreeList::RemoveRange (this=0x2904380 <tcmalloc::Static::central_cache_+4864>, start=start@entry=0x7f5a4f9b66e8, end=end@entry=0x7f5a4f9b66f0, N=32) at src/central_freelist.cc:248
#5  0x0000000001214be6 in tcmalloc::ThreadCache::FetchFromCentralCache (this=0x3007ac0, cl=4, byte_size=48, oom_handler=oom_handler@entry=0x136dbc0 <tcmalloc::cpp_throw_oom(unsigned long)>) at src/thread_cache.cc:126
#6  0x000000000136f29e in tcmalloc::ThreadCache::Allocate (oom_handler=0x136dbc0 <tcmalloc::cpp_throw_oom(unsigned long)>, cl=<optimized out>, size=<optimized out>, this=<optimized out>) at src/thread_cache.h:380
#7  malloc_fast_path<tcmalloc::cpp_throw_oom> (size=size@entry=40) at src/tcmalloc.cc:1855
#8  tc_new (size=size@entry=40) at src/tcmalloc.cc:1976
#9  0x0000000000f4ec7e in google::protobuf::internal::Mutex::Mutex (this=0xaf71c588) at google/protobuf/stubs/common.cc:366
#10 0x0000000000adc201 in google::protobuf::internal::MapFieldBase::MapFieldBase (this=0xaf71c570) at /root/thirdparty/include/google/protobuf/map_field.h:63
#11 0x0000000000adc13f in google::protobuf::internal::TypeDefinedMapFieldBase<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::TypeDefinedMapFieldBase
    (this=0xaf71c570) at /root/thirdparty/include/google/protobuf/map_field.h:181
#12 0x0000000000ac3329 in google::protobuf::internal::MapField<bigo::pb3::recommend::Item_InterveneInfoEntry_DoNotUse, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, (google::protobuf::internal::WireFormatLite::FieldType)9, (google::protobuf::internal::WireFormatLite::FieldType)9, 0>::MapField (this=0xaf71c570) at /root/thirdparty/include/google/protobuf/map_field.h:240
#13 0x0000000000a8e0ec in bigo::pb3::recommend::Item::Item (this=0xaf71c500) at recommend.pb.cc:3477
#14 0x0000000000ada335 in google::protobuf::Arena::CreateMessage<bigo::pb3::recommend::Item> (arena=0x0) at /root/thirdparty/include/google/protobuf/arena.h:288
#15 google::protobuf::Arena::CreateMaybeMessage<bigo::pb3::recommend::Item> (arena=0x0) at /root/thirdparty/include/google/protobuf/arena.h:671
#16 google::protobuf::Arena::CreateMaybeMessage<bigo::pb3::recommend::Item> (arena=0x0) at /root/thirdparty/include/google/protobuf/arena.h:681
#17 google::protobuf::internal::GenericTypeHandler<bigo::pb3::recommend::Item>::New (arena=0x0) at /root/thirdparty/include/google/protobuf/repeated_field.h:617
#18 0x0000000000ada2d9 in google::protobuf::internal::GenericTypeHandler<bigo::pb3::recommend::Item>::NewFromPrototype (arena=0x0) at /root/thirdparty/include/google/protobuf/repeated_field.h:647
#19 0x0000000000ae3980 in google::protobuf::internal::RepeatedPtrFieldBase::MergeFromInnerLoop<google::protobuf::RepeatedPtrField<bigo::pb3::recommend::Item>::TypeHandler> (this=0x7f5a4f9b6e50, our_elems=0xdccbe008, other_elems=0x780a6008, length=58255, 
    already_allocated=0) at /root/thirdparty/include/google/protobuf/repeated_field.h:1647
#20 0x0000000000adbb7e in google::protobuf::internal::RepeatedPtrFieldBase::MergeFromInternal (this=0x7f5a4f9b6e50, other=..., inner_loop=
    (void (google::protobuf::internal::RepeatedPtrFieldBase::*)(google::protobuf::internal::RepeatedPtrFieldBase * const, void **, void **, int, int)) 0xae38b0 <google::protobuf::internal::RepeatedPtrFieldBase::MergeFromInnerLoop<google::protobuf::RepeatedPtrField<bigo::pb3::recommend::Item>::TypeHandler>(void**, void**, int, int)>) at /root/thirdparty/include/google/protobuf/repeated_field.h:1619
#21 0x0000000000ae3895 in google::protobuf::internal::RepeatedPtrFieldBase::MergeFrom<google::protobuf::RepeatedPtrField<bigo::pb3::recommend::Item>::TypeHandler> (this=0x7f5a4f9b6e50, other=...)
    at /root/thirdparty/include/google/protobuf/repeated_field.h:1607
#22 0x0000000000acb1e8 in google::protobuf::RepeatedPtrField<bigo::pb3::recommend::Item>::MergeFrom (this=0x7f5a4f9b6e50, other=...) at /root/thirdparty/include/google/protobuf/repeated_field.h:2108
#23 0x0000000000acad7d in google::protobuf::RepeatedPtrField<bigo::pb3::recommend::Item>::RepeatedPtrField (this=0x7f5a4f9b6e50, other=...) at /root/thirdparty/include/google/protobuf/repeated_field.h:1916
#24 0x0000000000ab0eda in bigo::pb3::recommend::GetRecItemsRes::GetRecItemsRes (this=0x7f5a4f9b6e40, from=...) at recommend.pb.cc:12463
```
- Stack trace of other thread:
```
#0  0x0000000001215d76 in sys_futex (v3=0, a2=0x0, t=0x7f5a4f8b2ad0, v=<optimized out>, o=128, a=0x2904380 <tcmalloc::Static::central_cache_+4864>) at ./src/base/linux_syscall_support.h:2485
2485	in ./src/base/linux_syscall_support.h
(gdb) bt
#0  0x0000000001215d76 in sys_futex (v3=0, a2=0x0, t=0x7f5a4f8b2ad0, v=<optimized out>, o=128, a=0x2904380 <tcmalloc::Static::central_cache_+4864>) at ./src/base/linux_syscall_support.h:2485
#1  base::internal::SpinLockDelay (w=0x2904380 <tcmalloc::Static::central_cache_+4864>, value=2, loop=<optimized out>) at ./src/base/spinlock_linux-inl.h:84
#2  0x0000000001215c56 in SpinLock::SlowLock (this=0x2904380 <tcmalloc::Static::central_cache_+4864>) at src/base/spinlock.cc:119
#3  0x000000000120c388 in SpinLock::Lock (this=0x2904380 <tcmalloc::Static::central_cache_+4864>) at src/base/spinlock.h:71
#4  SpinLockHolder::SpinLockHolder (l=0x2904380 <tcmalloc::Static::central_cache_+4864>, this=<synthetic pointer>) at src/base/spinlock.h:133
#5  tcmalloc::CentralFreeList::InsertRange (this=0x2904380 <tcmalloc::Static::central_cache_+4864>, start=0x87b96c00, end=0xab9c0db0, N=32) at src/central_freelist.cc:232
#6  0x0000000001214dd1 in tcmalloc::ThreadCache::ReleaseToCentralCache (this=this@entry=0x3008700, src=src@entry=0x3008780, cl=<optimized out>, N=<optimized out>, N@entry=32) at src/thread_cache.cc:207
#7  0x0000000001215155 in tcmalloc::ThreadCache::ListTooLong (this=0x3008700, list=0x3008780, cl=<optimized out>) at src/thread_cache.cc:164
#8  0x0000000000adc235 in google::protobuf::internal::TypeDefinedMapFieldBase<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::~TypeDefinedMapFieldBase
    (this=0xdd782ab8) at /root/thirdparty/include/google/protobuf/map_field.h:183
#9  0x0000000000ac341d in google::protobuf::internal::MapField<bigo::pb3::recommend::Item_RoomColumnValueEntry_DoNotUse, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, (google::protobuf::internal::WireFormatLite::FieldType)9, (google::protobuf::internal::WireFormatLite::FieldType)9, 0>::~MapField (this=0xdd782ab8) at /root/thirdparty/include/google/protobuf/map_field.h:212
#10 0x0000000000a8fcfe in bigo::pb3::recommend::Item::~Item (this=0xdd782a00) at recommend.pb.cc:3652
#11 0x0000000000a901f9 in bigo::pb3::recommend::Item::~Item (this=0xdd782a00) at recommend.pb.cc:3649
#12 0x0000000000ae370a in google::protobuf::internal::GenericTypeHandler<bigo::pb3::recommend::Item>::Delete (value=0xdd782a00, arena=0x0) at /root/thirdparty/include/google/protobuf/repeated_field.h:623
#13 0x0000000000ae3696 in google::protobuf::internal::RepeatedPtrFieldBase::Destroy<google::protobuf::RepeatedPtrField<bigo::pb3::recommend::Item>::TypeHandler> (this=0x7f5a4f8b2e50)
    at /root/thirdparty/include/google/protobuf/repeated_field.h:1473
#14 0x0000000000acacd9 in google::protobuf::RepeatedPtrField<bigo::pb3::recommend::Item>::~RepeatedPtrField (this=0x7f5a4f8b2e50) at /root/thirdparty/include/google/protobuf/repeated_field.h:1934
#15 0x0000000000ab174c in bigo::pb3::recommend::GetRecItemsRes::~GetRecItemsRes (this=0x7f5a4f8b2e40) at recommend.pb.cc:12530
```

**Comment by alk** [comment]
Hi. Thanks for report. I'll need stack traces from all thread to see what caused deadlock. Assuming it is deadlock.

I.e. we need to see thread that has whatever spinlock that your first thread is sleeping on and we need to see why it is stuck.

**Comment by alk** [comment]
Closing due to inactivity. Do reopen if you're able to get me what we need. We need all backtraces from all threads or at least a thread that is apparently holding the lock. I.e. those 2 backtraces are just victims. We need the guy who actually did this (has lock and blocked somewhere else; where is the quesiton)
