### ISSUE TITLE
A bug in gperftools-2.0

### ISSUE THREAD

**Issue by ben741863140** [gperftools/gperftools#1134]
I'm running a program with tcmalloc2.0 while there is a segmentation fault. here is my program
@alk 
```C++
#include <bits/stdc++.h>
#include <thread>
#include <sys/time.h>
// #include "google/malloc_extension.h"

int cnt, enter;
const int MaxSize = 1024 * 1024 * 2; // 2M
const int MinSize = 1024 * 256;// 256K
const int Thread = 2;
const int SpanLen = 1e9 + 10;
const long long Mem = 1LL * 1024 * 1024 * 1024 * 6;//5G

struct timeval started, ended;

void push(int pos, int x) {
	long long num = 0;
	std::vector<char *> v;
	v.clear();
	for (int i = pos; i < SpanLen; ++i) {
		char *a = new char[MaxSize + x];
		memset(a, 0, sizeof(a));
		v.push_back(a);
		num += MaxSize + x;
		if (num >= Mem) {
			pos = i + 1;
			break;
		}
	}
	for (int i = 0; i < v.size(); ++i) {
		delete [] v[i];
	}
//	MallocExtension::instance()->ReleaseFreeMemory();
	push(pos, x + 1);
	return;
}

inline void init() {
	cnt = 0;
	enter = 0;
	push(0, 0);
	return ;
}

void new_t() {
	enter++;
	srand(0);
	int Size = rand() % (MaxSize - MaxSize / 2 + 1) + MaxSize / 2;
	char *a = new char[Size];
	memset(a, 0, sizeof(a));
	delete [] a;
	cnt++;
}

int main(int argc, char** argv) {
	init();
	std::cout << "Allocate done!" << std::endl;
	gettimeofday(&started, NULL);
	while (enter < Thread) {
		std::thread t(new_t);
		t.detach();
	}
	while (cnt < Thread);
	gettimeofday(&ended, NULL);
	std::cout << "Time cost:" << (ended.tv_sec * 1e6 + ended.tv_usec) - (started.tv_sec * 1e6 + started.tv_usec) << "us" << std:: endl;
	exit(0);
	return 0;
}
```
the gdb show that there is something unexpected happened in pagemap
```
Program received signal SIGSEGV, Segmentation fault.
set (this=0x6b3000, v=0x660200, k=969) at src/pagemap.h:263
263         reinterpret_cast<Leaf*>(root_->ptrs[i1]->ptrs[i2])->values[i3] = v;
Missing separate debuginfos, use: debuginfo-install glibc-2.17-196.tl2.3.x86_64 libgcc-4.8.5-5.tl2.x86_64 libstdc++-4.8.5-5.tl2.x86_64
(gdb) bt
#0  set (this=0x6b3000, v=0x660200, k=969) at src/pagemap.h:263
#1  RecordSpan (span=0x660200, this=0x6b3000) at src/page_heap.h:258
#2  tcmalloc::PageHeap::Carve (this=0x6b3000, span=0x65a080, n=2) at src/page_heap.cc:205
#3  0x000000000040dc78 in tcmalloc::PageHeap::New (this=0x6b3000, n=n@entry=2) at src/page_heap.cc:119
#4  0x0000000000408c2b in tcmalloc::CentralFreeList::Populate (this=this@entry=0x637ac0 <tcmalloc::Static::central_cache_+68672>) at src/central_freelist.cc:318
#5  0x0000000000408e18 in tcmalloc::CentralFreeList::FetchFromSpansSafe (this=this@entry=0x637ac0 <tcmalloc::Static::central_cache_+68672>) at src/central_freelist.cc:285
#6  0x0000000000408e96 in tcmalloc::CentralFreeList::RemoveRange (this=0x637ac0 <tcmalloc::Static::central_cache_+68672>, start=start@entry=0x7fffffffe1d0,
    end=end@entry=0x7fffffffe1d8, N=1) at src/central_freelist.cc:263
#7  0x000000000040f735 in tcmalloc::ThreadCache::FetchFromCentralCache (this=0x75d100, cl=<optimized out>, byte_size=2048) at src/thread_cache.cc:162
#8  0x0000000000415358 in Allocate (cl=<optimized out>, size=<optimized out>, this=<optimized out>) at src/thread_cache.h:341
#9  do_malloc (size=<optimized out>) at src/tcmalloc.cc:1105
#10 cpp_alloc (nothrow=false, size=2048) at src/tcmalloc.cc:1391
#11 tc_new (size=2048) at src/tcmalloc.cc:1567
#12 0x0000000000404176 in __gnu_cxx::new_allocator<char*>::allocate (this=0x7fffffffe370, __n=256) at /usr/include/c++/4.8.2/ext/new_allocator.h:104
#13 0x0000000000403df1 in std::_Vector_base<char*, std::allocator<char*> >::_M_allocate (this=0x7fffffffe370, __n=256) at /usr/include/c++/4.8.2/bits/stl_vector.h:168
#14 0x000000000040385c in std::vector<char*, std::allocator<char*> >::_M_emplace_back_aux<char* const&> (this=0x7fffffffe370) at /usr/include/c++/4.8.2/bits/vector.tcc:404
#15 0x00000000004034eb in std::vector<char*, std::allocator<char*> >::push_back (this=0x7fffffffe370, __x=@0x7fffffffe368: 0x108d6000 "")
    at /usr/include/c++/4.8.2/bits/stl_vector.h:911
#16 0x0000000000402ec6 in push (pos=0, x=0) at main.cpp:31
#17 0x00000000004033c4 in init () at main.cpp:53
#18 0x0000000000403055 in main (argc=1, argv=0x7fffffffe4f8) at main.cpp:71
```

**Comment by romange** [comment]
so stop using 2012 version and update to 2.7

**Comment by alk** [comment]
Closing as wont fix. I'm cleaning up tickets and there is quite a few, and, sorry, I cannot afford looking in depth at ticket against version that doesn't matter anymore.

Reopen if you have something to say about up to date version.
