### ISSUE TITLE
gperftools 2.8 hangs on fork() and system() RHEL6 and RHEL7

### ISSUE THREAD

**Issue by CaptainMalick** [gperftools/gperftools#1206]
Hello, 
I'm currently running into an issue where a program will hang on fork() and system() when run with the profiler. I have tried on RHEL6 and RHEL7. I've included partial stack traces below. This doesn't seem to occur in every instance either fork or system, but happens consistently in certain instances. These hangs do no occur when run without the profiler. 

#0  0x0000003365eacb1d in fork () from /lib64/libc.so.6
#1  0x0000003365e685f7 in _IO_proc_open@@GLIBC_2.2.5 () from /lib64/libc.so.6
#2  0x0000003365e688e9 in popen@@GLIBC_2.2.5 () from /lib64/libc.so.6

#0  0x0000003c8083e5ca in do_system () from /lib64/libc.so.6
#1  0x0000003c8083e940 in system () from /lib64/libc.so.6

**Comment by alk** [comment]
Thanks for bug report. Are you referring to cpu profiler or heap profiler (or some other profiler)?
