### ISSUE TITLE
Segmentation fault after upgrade from 2.7 to 2.8

### ISSUE THREAD

**Issue by sduzh** [gperftools/gperftools#1209]
```
#0  tcmalloc::DLL_Remove (span=0x6c539b0) at src/span.cc:67
#1  0x0000000004480540 in tcmalloc::PageHeap::CheckAndHandlePreMerge (this=<optimized out>, span=<optimized out>, other=0x6c539b0) at src/page_heap.cc:349
#2  0x00000000044803b0 in tcmalloc::PageHeap::MergeIntoFreeList (this=this@entry=0x688a200 <tcmalloc::Static::pageheap_>, span=span@entry=0x6c539e0) at src/page_heap.cc:382
#3  0x00000000044804e6 in tcmalloc::PageHeap::ReleaseSpan (this=0x688a200 <tcmalloc::Static::pageheap_>, span=span@entry=0x6c539e0) at src/page_heap.cc:511
#4  0x000000000448056c in tcmalloc::PageHeap::CheckAndHandlePreMerge (this=<optimized out>, span=<optimized out>, other=0x6c539e0) at src/page_heap.cc:339
#5  0x0000000004480421 in tcmalloc::PageHeap::MergeIntoFreeList (this=this@entry=0x688a200 <tcmalloc::Static::pageheap_>, span=0x6c539b0) at src/page_heap.cc:392
#6  0x0000000004480a44 in tcmalloc::PageHeap::Delete (this=0x688a200 <tcmalloc::Static::pageheap_>, span=<optimized out>) at src/page_heap.cc:318
#7  0x0000000004475bd8 in tcmalloc::CentralFreeList::ReleaseToSpans (this=this@entry=0x6a0dce0 <tcmalloc::Static::central_cache_+2432>, object=<optimized out>) at src/central_freelist.cc:140
#8  0x0000000004475c9b in tcmalloc::CentralFreeList::ReleaseListToSpans (this=this@entry=0x6a0dce0 <tcmalloc::Static::central_cache_+2432>, start=<optimized out>, start@entry=0x7499d20) at src/central_freelist.cc:85
#9  0x0000000004475f77 in tcmalloc::CentralFreeList::InsertRange (this=0x6a0dce0 <tcmalloc::Static::central_cache_+2432>, start=0x7499d20, end=0x7a9e050, N=<optimized out>) at src/central_freelist.cc:241
#10 0x0000000004482a3e in tcmalloc::ThreadCache::ReleaseToCentralCache (this=this@entry=0x6c91080, src=src@entry=0x6c910c0, cl=<optimized out>, N=20, N@entry=32) at src/thread_cache.cc:207
#11 0x0000000004482d95 in tcmalloc::ThreadCache::ListTooLong (this=0x6c91080, list=0x6c910c0, cl=<optimized out>) at src/thread_cache.cc:164
#12 0x0000000003e0368d in CRYPTO_free ()
#13 0x0000000003f03959 in value_free_stack_LHASH_DOALL ()
#14 0x0000000003e4c5c1 in lh_doall ()
#15 0x0000000003f03ccc in _CONF_free_data ()
#16 0x0000000003f044ee in def_destroy ()
#17 0x0000000003e8e43f in CONF_modules_load_file ()
#18 0x0000000003a8aaac in Curl_ossl_init ()
...
```

```
(gdb) f 0
#0  tcmalloc::DLL_Remove (span=0x6c539b0) at src/span.cc:67
67        span->prev->next = span->next;
(gdb) p *span
$2 = {
  start = 15695,
  length = 1,
  next = 0x0,
  prev = 0x0,
  {
    objects = 0x7a9e040,
    span_iter_space = "@\340\251\a\000\000\000"
  },
  refcount = 0,
  sizeclass = 0,
  location = 2,
  sample = 0,
  has_span_iter = false
}
```

**Comment by hellozhuzhu** [comment]
Hello, I have the same problem when I upgraded to version 2.8. How did you solve your problem? Can you give me some ideas?
