### ISSUE TITLE
invalidfree when use _nss_dns_gethostbyname4_r

### ISSUE THREAD

**Issue by StydyOnce** [gperftools/gperftools#1238]
stack is
(gdb) bt
#0  0x00007ffff49567bb in raise () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff4941535 in abort () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00007ffff7bfea66 in tcmalloc::Log(tcmalloc::LogMode, char const*, int, tcmalloc::LogItem, tcmalloc::LogItem, tcmalloc::LogItem, tcmalloc::LogItem) () from /home/app/libtcmalloc.so.4
#3  0x00007ffff7bf3644 in (anonymous namespace)::InvalidFree(void*) () from /home/app/libtcmalloc.so.4
#4  0x00007fffd0ac0240 in _nss_dns_gethostbyname4_r () from /lib/x86_64-linux-gnu/libnss_dns.so.2
#5  0x00007ffff4a01e0a in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#6  0x00007ffff4a02e37 in getaddrinfo () from /lib/x86_64-linux-gnu/libc.so.6
#7  0x000000000051ec04 in Curl_getaddrinfo_ex ()
#8  0x00000000005205fc in getaddrinfo_thread ()
#9  0x000000000054bf4b in curl_thread_create_thunk ()
#10 0x00007ffff5bd0fa3 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#11 0x00007ffff4a184cf in clone () from /lib/x86_64-linux-gnu/libc.so.6

and my way is by LD_PRELOAD
thank you for your  answer
@alk @tmm1

**Comment by StydyOnce** [comment]
i found problem;
cause i use libcurl.a and libcurl.so in different library. modify .a to .so is correct.
really reason who know it can explain it,thank you
