### ISSUE TITLE
TCMalloc LD_PRELOAD deadlock 

### ISSUE THREAD

**Issue by dautovri** [gperftools/gperftools#1248]
Alpine Linux Docker 
`gdb ls `
```
set exec-wrapper env LD_PRELOAD="/usr/lib/libtcmalloc.so"
run
```
```
(gdb) bt
#0  __cp_end () at src/thread/x86_64/syscall_cp.s:29
#1  0x00007ffff7fb9cf4 in __syscall_cp_c (nr=35, u=140737488347680, v=0, 
    w=<optimized out>, x=<optimized out>, y=<optimized out>, z=0)
    at src/thread/pthread_cancel.c:33
#2  0x00007ffff7fbdbf4 in __clock_nanosleep (clk=clk@entry=0, 
    flags=flags@entry=0, req=req@entry=0x7fffffffe220, rem=rem@entry=0x0)
    at src/time/clock_nanosleep.c:34
#3  0x00007ffff7fbdf68 in nanosleep (req=req@entry=0x7fffffffe220, 
    rem=rem@entry=0x0) at src/time/nanosleep.c:6
#4  0x00007ffff7d960d7 in base::internal::SpinLockDelay (
    w=0x7ffff7f5ab28 <tcmalloc::Static::pageheap_lock_>, value=2, loop=1560)
    at ./src/base/spinlock_linux-inl.h:88
#5  0x00007ffff7d96035 in SpinLock::SlowLock (
    this=0x7ffff7f5ab28 <tcmalloc::Static::pageheap_lock_>)
    at src/base/spinlock.cc:118
#6  0x00007ffff7d8b44c in SpinLock::Lock (this=<optimized out>)
    at src/base/spinlock.h:71
#7  SpinLockHolder::SpinLockHolder (l=<optimized out>, 
    this=<synthetic pointer>) at src/base/spinlock.h:133
#8  tcmalloc::ThreadCache::InitModule () at src/thread_cache.cc:286
#9  0x00007ffff7d8b5ed in tcmalloc::ThreadCache::CreateCacheIfNecessary ()
    at src/thread_cache.cc:329
#10 0x00007ffff7d99ffd in tcmalloc::ThreadCache::GetCache ()
--Type <RET> for more, q to quit, c to continue without paging--cQ
    at src/thread_cache.h:437
#11 (anonymous namespace)::do_malloc (size=38952) at src/tcmalloc.cc:1369
#12 tcmalloc::do_allocate_full<tcmalloc::malloc_oom> (size=38952) at src/tcmalloc.cc:1777
#13 tcmalloc::allocate_full_malloc_oom (size=38952) at src/tcmalloc.cc:1793
#14 0x00007ffff7bc27c5 in ?? () from /usr/lib/libgcc_s.so.1
#15 0x00007ffff7bc2f3f in _Unwind_Find_FDE () from /usr/lib/libgcc_s.so.1
#16 0x00007ffff7bc09fa in ?? () from /usr/lib/libgcc_s.so.1
#17 0x00007ffff7bc12e1 in ?? () from /usr/lib/libgcc_s.so.1
#18 0x00007ffff7bc1a62 in _Unwind_Backtrace () from /usr/lib/libgcc_s.so.1
#19 0x00007ffff7d9629a in GetStackTrace_libgcc (result=<optimized out>, max_depth=<optimized out>, skip_count=<optimized out>) at src/stacktrace_libgcc-inl.h:100
#20 0x00007ffff7d96a83 in GetStackTrace (result=result@entry=0x7ffff73d5010, max_depth=max_depth@entry=30, skip_count=skip_count@entry=3) at src/stacktrace.cc:295
#21 0x00007ffff7d88aae in tcmalloc::RecordGrowth (growth=1048576) at src/page_heap.cc:610
#22 tcmalloc::PageHeap::GrowHeap (n=<optimized out>, this=0x7ffff7db0940 <tcmalloc::Static::pageheap_>) at src/page_heap.cc:636
#23 tcmalloc::PageHeap::GrowHeap (this=0x7ffff7db0940 <tcmalloc::Static::pageheap_>, n=<optimized out>) at src/page_heap.cc:616
#24 0x00007ffff7d88d6b in tcmalloc::PageHeap::New (this=0x7ffff7db0940 <tcmalloc::Static::pageheap_>, n=n@entry=1) at src/page_heap.cc:154
#25 0x00007ffff7d86d35 in tcmalloc::CentralFreeList::Populate (this=0x7ffff7f34da0 <tcmalloc::Static::central_cache_+4864>) at src/static_vars.h:73
#26 0x00007ffff7d86f28 in tcmalloc::CentralFreeList::FetchFromOneSpansSafe (end=0x7fffffffea70, start=0x7fffffffea68, N=1, this=0x7ffff7f34da0 <tcmalloc::Static::central_cache_+4864>) at src/central_freelist.cc:282
#27 tcmalloc::CentralFreeList::FetchFromOneSpansSafe (this=0x7ffff7f34da0 <tcmalloc::Static::central_cache_+4864>, N=1, start=0x7fffffffea68, end=0x7fffffffea70) at src/central_freelist.cc:279
#28 0x00007ffff7d86fcc in tcmalloc::CentralFreeList::RemoveRange (this=0x7ffff7f34da0 <tcmalloc::Static::central_cache_+4864>, start=start@entry=0x7fffffffea68, end=end@entry=0x7fffffffea70, N=1) at src/central_freelist.cc:262
#29 0x00007ffff7d8a882 in tcmalloc::ThreadCache::FetchFromCentralCache (this=this@entry=0x7ffff73f5000, cl=cl@entry=4, byte_size=byte_size@entry=48, oom_handler=oom_handler@entry=0x7ffff7d798f0 <(anonymous namespace)::nop_oom_handler(size_t)>) at src/static_vars.h:62
#30 0x00007ffff7d9a045 in tcmalloc::ThreadCache::Allocate (oom_handler=0x7ffff7d798f0 <(anonymous namespace)::nop_oom_handler(size_t)>, cl=4, size=48, this=0x7ffff73f5000) at src/thread_cache.h:380
#31 (anonymous namespace)::do_malloc (size=40) at src/tcmalloc.cc:1386
#32 tcmalloc::do_allocate_full<tcmalloc::malloc_oom> (size=40) at src/tcmalloc.cc:1777
#33 tcmalloc::allocate_full_malloc_oom (size=40) at src/tcmalloc.cc:1793
#34 0x00007ffff7fb95c9 in pthread_atfork (prepare=0x7ffff7d89960 <tcmalloc::CentralCacheLockAll()>, parent=0x7ffff7d899d0 <tcmalloc::CentralCacheUnlockAll()>, child=0x7ffff7d899d0 <tcmalloc::CentralCacheUnlockAll()>) at src/thread/pthread_atfork.c:36
#35 0x00007ffff7d97d03 in perftools_pthread_atfork (before=<optimized out>, parent_after=<optimized out>, child_after=<optimized out>) at src/maybe_threads.cc:172
#36 0x00007ffff7d8b5ed in tcmalloc::ThreadCache::CreateCacheIfNecessary () at src/thread_cache.cc:329
#37 0x00007ffff7d99ffd in tcmalloc::ThreadCache::GetCache () at src/thread_cache.h:437
#38 (anonymous namespace)::do_malloc (size=72704) at src/tcmalloc.cc:1369
#39 tcmalloc::do_allocate_full<tcmalloc::malloc_oom> (size=72704) at src/tcmalloc.cc:1777
#40 tcmalloc::allocate_full_malloc_oom (size=72704) at src/tcmalloc.cc:1793
#41 0x00007ffff7c89138 in ?? () from /usr/lib/libstdc++.so.6
#42 0x00007ffff7fc1060 in do_init_fini (queue=<optimized out>) at ldso/dynlink.c:1493
#43 0x00007ffff7fc2308 in __libc_start_init () at ldso/dynlink.c:1506
#44 0x00007ffff7f851e5 in libc_start_main_stage2 (main=0x555555561e2c, argc=1, argv=0x7fffffffed38) at src/env/__libc_start_main.c:91
#45 0x000055555556172e in ?? ()
#46 0x0000000000000001 in ?? ()
#47 0x00007fffffffef0d in ?? ()
#48 0x0000000000000000 in ?? ()
(gdb) 
```

**Comment by alk** [comment]
Can you please post config.log?

**Comment by alk** [comment]
aha, this is actually straightforward. emergency malloc should be enabled by default even for libgcc-based unwinder.

**Comment by dautovri** [comment]
> aha, this is actually straightforward. emergency malloc should be enabled by default even for libgcc-based unwinder.

Thank you ./configure --enable-emergency-malloc sort the problem.

**Comment by dautovri** [comment]
> aha, this is actually straightforward. emergency malloc should be enabled by default even for libgcc-based unwinder.

Thank you ./configure --enable-emergency-malloc sort the problem.
