### ISSUE TITLE
Cpu Profiler Segmentation fault with libunwind 1.0.1

### ISSUE THREAD

**Issue by Pramy** [gperftools/gperftools#1255]
Centos 7 kennel 3.10 unwind 1.0.1

```
#0  access_mem (as=0x0, addr=139862761140224, val=0x7f345631cce8, write=4, arg=0x7f345631cd20) at x86_64/Ginit.c:173
#1  0x0000000000a26e38 in is_plt_entry (c=<optimized out>) at x86_64/Gstep.c:43
#2  _ULx86_64_step (cursor=<optimized out>) at x86_64/Gstep.c:122
#3  0x0000000000a09faa in GetStackTraceWithContext (result=0x7f345631d518, max_depth=63, skip_count=<optimized out>,
    ucp=<optimized out>) at src/stacktrace_libunwind-inl.h:114
#4  0x0000000000a07663 in CpuProfiler::prof_handler (sig=<optimized out>, signal_ucontext=0x7f345631d780,
    cpu_profiler=<optimized out>) at src/profiler.cc:280
#5  0x0000000000a08a28 in ProfileHandler::SignalHandler (sig=27, sinfo=0x7f345631d8b0, ucontext=0x7f345631d780)
    at src/profile-handler.cc:501
#6  <signal handler called>
#7  0x00007f496761e380 in free@plt () from /lib64/libc.so.6
#8  0x00007f49676466f1 in vfprintf () from /lib64/libc.so.6
#9  0x00007f496766d9cb in vsprintf () from /lib64/libc.so.6
#10 0x00007f4967650e07 in sprintf () from /lib64/libc.so.6
```

**Comment by alk** [comment]
Sometimes compiler generate faulty unwind info. And also possibly libunwind has bugs too. Nothing we can do at the moment. Try upgrading libunwind.
