### ISSUE TITLE
tcmalloc crash bus error - central free list contains read-only address from code-segment

### ISSUE THREAD

**Issue by pchoudhary-jnpr** [gperftools/gperftools#1364]
Hi,
We have a hit a crash with tcmalloc, where central free list is corrupted. One of the node is holding the address of vtable which is statically allocated. Can you please check in which scenario we can hit this ? 
We have run our application under ASAN and didn't hit any double or write after free.

`#0  tcmalloc::CentralFreeList::FetchFromOneSpans (
    this=this@entry=0x7f583c428f80 <tcmalloc::Static::central_cache_+6080>,
    N=N@entry=32, start=start@entry=0x7f583223f208,
    end=end@entry=0x7f583223f210) at src/central_freelist.cc:301
#1  0x00007f583c07b67a in tcmalloc::CentralFreeList::FetchFromOneSpansSafe (
    this=this@entry=0x7f583c428f80 <tcmalloc::Static::central_cache_+6080>,
    N=N@entry=32, start=start@entry=0x7f583223f208, end=0x7f583223f210)
    at src/central_freelist.cc:282
#2  0x00007f583c07b730 in tcmalloc::CentralFreeList::RemoveRange (
    this=0x7f583c428f80 <tcmalloc::Static::central_cache_+6080>,
    start=start@entry=0x7f583223f208, end=end@entry=0x7f583223f210, N=32)
    at src/central_freelist.cc:264
#3  0x00007f583c07f01c in tcmalloc::ThreadCache::FetchFromCentralCache (
    this=0x2f1ae40, cl=<optimized out>, byte_size=64,
    oom_handler=oom_handler@entry=0x7f583c08d480 <tcmalloc::cpp_throw_oom(unsigned long)>) at src/thread_cache.cc:126
#4  0x00007f583c08ec0f in Allocate (
    oom_handler=0x7f583c08d480 <tcmalloc::cpp_throw_oom(unsigned long)>,
    cl=<optimized out>, size=<optimized out>, this=<optimized out>)
    at src/thread_cache.h:380
#5  malloc_fast_path<tcmalloc::cpp_throw_oom> (size=size@entry=64)
    at src/tcmalloc.cc:1855
#6  tc_new (size=size@entry=64) at src/tcmalloc.cc:1976`

(gdb) f 0
#0  tcmalloc::CentralFreeList::FetchFromOneSpans (
    this=this@entry=0x7f583c428f80 <tcmalloc::Static::central_cache_+6080>,
    N=N@entry=32, start=start@entry=0x7f583223f208,
    end=end@entry=0x7f583223f210) at src/central_freelist.cc:301
301     in src/central_freelist.cc
(gdb) p span
$2 = (tcmalloc::Span *) 0x6e427b60
(gdb) set pr ob on
(gdb) p $2->objects
$3 = (void *) 0x34ae8a40
(gdb) p *((void**)$3)
$4 = (void *) 0x34ae8c80
(gdb) p *((void**)$4)
$5 = (void *) 0x34ae9740
(gdb) p *((void**)$19)
$20 = (void *) 0x34ae8300
(gdb) p *((void**)$20)
$21 = (void *) **0x1936370 <vtable for InterVnStats+16>**
(gdb) p *((void**)$21)
$22 = (void *) **0x149f170 <InterVnStats::~InterVnStats()>**

Above address are not from heap, so not sure how are they present in central free list. Can you please help on this ?

**Comment by jimafrost** [comment]
FWIW, you are not alone; we have seen this same crash, which was not present for our application with gperftools 2.7.
