### ISSUE TITLE
tcmalloc crash at CheckCachedSizeClass

### ISSUE THREAD

**Issue by alk** [gperftools/gperftools#522]
Originally reported on Google Code with ID 519
```
#3  0x0000000000dc00a8 in google::FlushLogFilesUnsafe (min_severity=0) at thirdparty/glog-0.3.2/src/logging.cc:1511
#4  0x0000000000dc618c in google::(anonymous namespace)::FailureSignalHandler (signal_number=11,
signal_info=0x63712270, 
    ucontext=0x63712140) at thirdparty/glog-0.3.2/src/signalhandler.cc:324
#5  <signal handler called>
#6  0x00000000009d1bd4 in CheckCachedSizeClass (ptr=0x7fbdf92f28a0) at thirdparty/google-perftools-1.7/src/tcmalloc.cc:946
#7  0x00000000009d1c0e in CheckedMallocResult (result=0x7fbdf92f28a0) at thirdparty/google-perftools-1.7/src/tcmalloc.cc:950
#8  0x00000000009d225b in (anonymous namespace)::do_malloc (size=96) at thirdparty/google-perftools-1.7/src/tcmalloc.cc:1084
#9  0x00000000009d2ea6 in (anonymous namespace)::cpp_alloc (size=96, nothrow=false)
    at thirdparty/google-perftools-1.7/src/tcmalloc.cc:1360
#10 0x00000000009d5ff7 in MallocBlock::Allocate (size=48, type=-21308287)
    at thirdparty/google-perftools-1.7/src/debugallocation.cc:537
#11 0x00000000009d3942 in DebugAllocate (size=48, type=-21308287) at thirdparty/google-perftools-1.7/src/debugallocation.cc:970
#12 0x00000000009d6b26 in cpp_debug_alloc (size=48, new_type=-21308287, nothrow=false)
    at thirdparty/google-perftools-1.7/src/debugallocation.cc:1203
#13 0x0000000000e3d0e7 in operator new (size=48) at thirdparty/google-perftools-1.7/src/debugallocation.cc:1250
#14 0x000000000095a001 in __gnu_cxx::new_allocator<std::_Rb_tree_node<std::pair<torca::master::Job
const* const, unsigned int> > >::allocate (this=0x7fbe1b61d020, __n=1)
    at /usr/local/lib/gcc/x86_64-unknown-linux-gnu/4.5.1/../../../../include/c++/4.5.1/ext/new_allocator.h:89
#15 0x0000000000959be0 in std::_Rb_tree<torca::master::Job const*, std::pair<torca::master::Job
const* const, unsigned int>, std::_Select1st<std::pair<torca::master::Job const* const,
unsigned int> >, torca::master::JobCompare, std::allocator<std::pair<torca::master::Job
const* const, unsigned int> > >::_M_get_node (this=0x7fbe1b61d020)
    at /usr/local/lib/gcc/x86_64-unknown-linux-gnu/4.5.1/../../../../include/c++/4.5.1/bits/stl_tree.h:359
#16 0x00000000009590ef in std::_Rb_tree<torca::master::Job const*, std::pair<torca::master::Job
const* const, unsigned int>, std::_Select1st<std::pair<torca::master::Job const* const,
unsigned int> >, torca::master::JobCompare, std::allocator<std::pair<torca::master::Job
const* const, unsigned int> > >::_M_create_node (this=0x7fbe1b61d020, __x=...)

What steps will reproduce the problem?
I don't know how to reproduce it, it happened just once.


What is the expected output? What do you see instead?
My program crash at
return reinterpret_cast<Leaf*>(root_->ptrs[i1]->ptrs[i2])->values[i3];
values[i3] = 0xFFFFFFFFDEADBEAF。


What version of the product are you using? On what operating system?
I use google-perftools-1.7 on SUSE.

Please provide any additional information below.

```

Reported by `tyrionqq` on 2013-04-10 06:17:18

**Comment by alk** [comment]
Closing stale ticket.

Reopen if you can provide more info.
