### ISSUE TITLE
tcmalloc will coredump if I free memory at fork (with library dlopened with RTLD_DEEPBIND)

### ISSUE THREAD

**Issue by alk** [gperftools/gperftools#569]
Originally reported on Google Code with ID 566
```
What steps will reproduce the problem?
1. write a shared library,and load it with flag RTLD_NOW | RTLD_LOCAL | RTLD_DEEPBIND

2. write a loop function in the shared library, repeat malloc/write/free memory frequently
3. fork child process frequently at main program
4. compile and link tcmalloc 
5. if I don't link tcmalloc, my program will work normally

What is the expected output? What do you see instead?

after a short while, our program will coredump , core stack info:

#3  0x000000302af2e2ed in raise () from /lib64/tls/libc.so.6
#4  0x000000302af2fa3e in abort () from /lib64/tls/libc.so.6
#5  0x000000302af62db1 in __libc_message () from /lib64/tls/libc.so.6
#6  0x000000302af6888e in _int_free () from /lib64/tls/libc.so.6
#7  0x000000302af68af0 in free_atfork () from /lib64/tls/libc.so.6
#8  0x00007f5842d8fa7b in bsl::pool_allocator<char>::deallocate (this=0x7f584138a9d0,
__p=0x91ffa0 "sample_variable", size_=16)
    at ../../output/include/bsl/pool/bsl_poolalloc.h:129


What version of the product are you using? On what operating system?

google-perftools-1.7
gcc version 3.4.5 20051201 (Red Hat 3.4.5-2)
kernel: 2.6.32_1-7-0-0

Please provide any additional information below.




```

Reported by `leywar.liang` on 2013-08-22 23:53:13

**Comment by alk** [comment]
Timed out waiting for reply. Most likely issue is caused by unsupported usage (DEEPBIND-ing)
