### ISSUE TITLE
minimal program linked with tcmalloc hangs on osx 10.8.5 & gcc-4.7.1

### ISSUE THREAD

**Issue by alk** [gperftools/gperftools#577]
Originally reported on Google Code with ID 574
```
What steps will reproduce the problem?

1. write a simple program, test.c

    int main()
    {
        return 0;
    }

2. compile and link with tcmalloc

    gcc test.c -ltcmalloc -fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc
-fno-builtin-free

3. run compiled binary

    ./a.out

What is the expected output? What do you see instead?

    expected output: no output
    what we have: segmentation fault

What version of the product are you using? On what operating system?
 
 - gperftools (@326990b, 2013/09/14)
 - OSX 10.8.5 (Darwin Kernel Version 12.5.0)
 - gcc-4.7.1 (download from http://prdownloads.sourceforge.net/hpc/gcc-4.7-bin.tar.gz?download
)

Please provide any additional information below.

1. I ran it with gdb and pressed C-c and I had the following trace:

Program received signal SIGINT, Interrupt.
0x00007fff896d4386 in __semwait_signal ()
(gdb) bt
#0  0x00007fff896d4386 in __semwait_signal ()
#1  0x00007fff898787c8 in nanosleep ()
#2  0x0000000100018d00 in base::internal::SpinLockDelay (w=<value temporarily unavailable,
due to optimizations>, value=<value temporarily unavailable, due to optimizations>,
loop=<value temporarily unavailable, due to optimizations>) at spinlock_posix-inl.h:53

2. It worked without a problem when I linked with tcmalloc_minimal

```

Reported by `soonho.kong` on 2013-09-20 23:38:39

**Comment by alk** [comment]
Closing stale ticket.
