### ISSUE TITLE
tcmalloc SEGV in libunwind 

### ISSUE THREAD

**Issue by alk** [gperftools/gperftools#709]
Originally reported on Google Code with ID 706
```
What steps will reproduce the problem?
1. linking with tcmalloc_debug
2.
3.

What is the expected output? What do you see instead?

a SEGV arising out of of a definition of type : typedef std::queue


#0  0x00007f01b244a9ad in _ULx86_64_dwarf_find_save_locs () from /lib64/libunwind.so.8
#1  0x00007f01b244b219 in _ULx86_64_dwarf_step () from /lib64/libunwind.so.8
#2  0x00007f01b2447751 in _ULx86_64_step () from /lib64/libunwind.so.8
#3  0x00007f01b0b67aa3 in GetStackTrace(void**, int, int) () from /lib64/libtcmalloc_debug.so.4
#4  0x00007f01b0b4e301 in MallocBlock::ProcessFreeQueue(MallocBlock*, unsigned long,
int) () from /lib64/libtcmalloc_debug.so.4
#5  0x00007f01b0b6c67e in tc_delete () from /lib64/libtcmalloc_debug.so.4
#6  0x000000000040fca4 in deallocate (this=<optimized out>, __p=<optimized out>) at
/usr/include/c++/4.8.2/ext/new_allocator.h:110
#7  _M_deallocate_node (this=<optimized out>, __p=<optimized out>) at /usr/include/c++/4.8.2/bits/stl_deque.h:539
#8  _M_destroy_nodes (this=0x1f70aeb0, __nfinish=0x2561b60, __nstart=<optimized out>)
at /usr/include/c++/4.8.2/bits/stl_deque.h:642
#9  std::_Deque_base<ctx_t*, std::allocator<ctx_t*> >::~_Deque_base (this=0x1f70aeb0,
__in_chrg=<optimized out>) at /usr/include/c++/4.8.2/bits/stl_deque.h:565
#10 0x000000000044b805 in ~deque (this=0x1f70aeb0, __in_chrg=<optimized out>) at /usr/include/c++/4.8.2/bits/stl_deque.h:918


What version of the product are you using? On what operating system?

libtcmalloc.so.4.1.2

gcc (GCC) 4.8.2 20140120


Please provide any additional information below.


```

Reported by `gaurab.paul` on 2015-08-19 07:01:37

**Comment by alk** [comment]
Closing as stale ticket. And since this is likely application problem.
