### ISSUE TITLE
crash report: SLL_Next  at src/linked_list.h:44 

### ISSUE THREAD

**Issue by jameyli** [gperftools/gperftools#798]
occured when destruct a protobuf message  
```proto
message DBKVCommSetReq {
    optional uint32 tag = 1;
    optional string key = 2;
    optional string value = 3;
    optional int32 version = 4;
}

```
the code  generated by protoc: 
```c++
DBKVCommSetReq::~DBKVCommSetReq() {
  // @@protoc_insertion_point(destructor:killer.proto.DBKVCommSetReq)
  SharedDtor();
}

void DBKVCommSetReq::SharedDtor() {
  if (key_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete key_;
  }
  if (value_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete value_;
  }
  if (this != default_instance_) {
  }
}

```
crash at line: ``` delete value_; ```

version: 2.1
gcc: gcc (GCC) 4.4.6 20110731 (Red Hat 4.4.6-4)
os: Linux 3.10.83 
full stack info ：
```
#0  SLL_Next (this=0x2925098, src=0x2925128, cl=<value optimized out>, N=845) at src/linked_list.h:44
No locals.
#1  SLL_PopRange (this=0x2925098, src=0x2925128, cl=<value optimized out>, N=845) at src/linked_list.h:75
        i = <value optimized out>
        tmp = 0x4ffffffff
#2  PopRange (this=0x2925098, src=0x2925128, cl=<value optimized out>, N=845) at src/thread_cache.h:228
No locals.
#3  tcmalloc::ThreadCache::ReleaseToCentralCache (this=0x2925098, src=0x2925128, cl=<value optimized out>, N=845) at src/thread_cache.cc:229
        delta_bytes = 40560
        batch_size = 1365
        tail = <value optimized out>
        head = <value optimized out>
#4  0x00000000007810e7 in tcmalloc::ThreadCache::Scavenge (this=0x2925098) at src/thread_cache.cc:248
        drop = <value optimized out>
        list = 0x2925128
        lowmark = <value optimized out>
        cl = <value optimized out>
#5  0x000000000078a9fb in Deallocate (p=<value optimized out>) at src/thread_cache.h:391
        list = <value optimized out>
        size_headroom = <value optimized out>
        list_headroom = <value optimized out>
#6  do_free_helper (p=<value optimized out>) at src/tcmalloc.cc:1180
        span = <value optimized out>
        p = <value optimized out>
        cl = <value optimized out>
        invalid_free_fn = 0x7752f0 <(anonymous namespace)::InvalidFree(void*)>
#7  do_free_with_callback (p=<value optimized out>) at src/tcmalloc.cc:1210
        heap = 0x2925098
        invalid_free_fn = 0x7752f0 <(anonymous namespace)::InvalidFree(void*)>
#8  do_free (p=<value optimized out>) at src/tcmalloc.cc:1219
No locals.
#9  tc_delete (p=<value optimized out>) at src/tcmalloc.cc:1619
No locals.
#10 0x00000000006192e5 in _M_dispose (this=<value optimized out>)
    at /usr/lib/gcc/x86_64-redhat-linux/4.4.6/../../../../include/c++/4.4.6/bits/basic_string.h:236
No locals.
#11 ~basic_string (this=<value optimized out>) at /usr/lib/gcc/x86_64-redhat-linux/4.4.6/../../../../include/c++/4.4.6/bits/basic_string.h:503
No locals.
#12 killer::proto::DBKVCommSetReq::SharedDtor (this=<value optimized out>) at dbproxy.pb.cc:41694
No locals.
---Type <return> to continue, or q <return> to quit---
#13 0x0000000000619354 in killer::proto::DBKVCommSetReq::~DBKVCommSetReq (this=0x34e6ae8, __in_chrg=<value optimized out>) at dbproxy.pb.cc:41686
No locals.
```

**Comment by alk** [comment]
Hi. Issues like that are usually due to application bugs. For example dangling pointer may cause your app to damage linked list used to organize freed objects.

Have you tried running your application under address sanitizer or similar tool?

**Comment by orifin** [comment]
We are seeing similar crash with the same perftools version (2.1) and similar gcc.
Did you find it to be something in your app or an actual bug in tcmalloc ?

**Comment by alk** [comment]
Closing as stale ticket.
