### ISSUE TITLE
crash in tcmalloc

### ISSUE THREAD

**Issue by shivakumarnc** [gperftools/gperftools#837]
I am seeing the crash while allocating memory (on stack) even valgrind log point to same method.I am not understanding why its crashing here.Any inputs will be of great help.
(gdb) bt
#0  0x0000003e4900e50b in raise () from /lib64/libpthread.so.0
#1  0x00000000006e4aa7 in sig_segv_handler (signo=11) at messagedump.cpp:326
#2  <signal handler called>
#3  tcmalloc::CentralFreeList::FetchFromOneSpans (this=0x7f5ad41c11e0, N=2, start=0x7f5ad05a0d20, end=0x7f5ad05a0d18) at src/central_freelist.cc:301
#4  0x00007f5ad3f87e78 in tcmalloc::CentralFreeList::FetchFromOneSpansSafe (this=0x7f5ad41c1220, N=2, start=0x7f5ad05a0d20, end=0x7f5ad05a0d18) at src/central_freelist.cc:282
#5  0x00007f5ad3f87f71 in tcmalloc::CentralFreeList::RemoveRange (this=0x7f5ad41c11e0, start=0x7f5ad05a0d20, end=0x7f5ad05a0d18, N=2) at src/central_freelist.cc:264
#6  0x00007f5ad3f8cd37 in tcmalloc::ThreadCache::FetchFromCentralCache (this=0x19eaea0, cl=27, byte_size=640) at src/thread_cache.cc:166
#7  0x00007f5ad3fa192b in Allocate (size=573) at src/thread_cache.h:365
#8  do_malloc_small (size=573) at src/tcmalloc.cc:1145
#9  do_malloc_no_errno (size=573) at src/tcmalloc.cc:1158
#10 do_malloc (size=573) at src/tcmalloc.cc:1173
#11 do_malloc_or_cpp_alloc (size=573) at src/tcmalloc.cc:1081
#12 tc_malloc (size=573) at src/tcmalloc.cc:1670
#13 0x00000000004bfa55 in MavMemoryMgr::alloc (this=0xbeace0, bytes=573) at memoryPool.cpp:1187
#14 0x00000000004bd779 in mavMemAlloc (size=573) at memoryPool.cpp:227
#15 0x00000000004c0458 in mxAlloc_trace (aSize=573, aId=538968180, aLine=101) at memoryPool.cpp:1486

==9248== Invalid read of size 8
==9248==    at 0x5295507: tcmalloc::CentralFreeList::FetchFromSpans() (central_freelist.cc:298)
==9248==    by 0x5295A8C: tcmalloc::CentralFreeList::FetchFromSpansSafe() (central_freelist.cc:283)
==9248==    by 0x5295B64: tcmalloc::CentralFreeList::RemoveRange(void**, void**, int) (central_freelist.cc:263)
==9248==    by 0x529A276: tcmalloc::ThreadCache::FetchFromCentralCache(unsigned long, unsigned long) (thread_cache.cc:162)
==9248==    by 0x52AE8F7: malloc (in /data/IMS/exports/images/rms-c.10.0.7.0-wrlinux_4_3_x86_64/AM_sw/bin/libtcmalloc.so.4)
==9248==    by 0x4BFB00: MavMemoryMgr::alloc(unsigned long) (memoryPool.cpp:1187)
==9248==    by 0x4BD824: mavMemAlloc (memoryPool.cpp:227)
==9248==    by 0x4C0503: mxAlloc_trace(unsigned int, unsigned int, unsigned int) (memoryPoo

**Comment by alk** [comment]
Please try running your program with valgrind or address sanitizer but without tcmalloc. Most likely it will help you find bug in your program.

**Comment by ZefengWang** [comment]
I also have the same problem SIGSEGV fault in program whthin a tcmalloc env

```
#0  0x0000fffff7d88dac in tcmalloc::CentralFreeList::FetchFromOneSpans(int, void**, void**) (this=0xfffff7dc6508 <tcmalloc::Static::central_cache_+20672>, N=7, start=0xffffd65b60b8, end=0xffffd65b60b0)
    at ./../src/erftools-2-908ada5f35.clean/src/central_freelist.cc:299
#1  0x0000fffff7d88d10 in tcmalloc::CentralFreeList::FetchFromOneSpansSafe(int, void**, void**) (this=0xfffff7dc6508 <tcmalloc::Static::central_cache_+20672>, N=7, start=0xffffd65b60b8, end=0xffffd65b60b0)
    at ./../src/erftools-2-908ada5f35.clean/src/central_freelist.cc:280
#2  0x0000fffff7d88c40 in tcmalloc::CentralFreeList::RemoveRange(void**, void**, int) (this=0xfffff7dc6508 <tcmalloc::Static::central_cache_+20672>, start=0xffffd65b60b8, end=0xffffd65b60b0, N=7)
    at ./../src/erftools-2-908ada5f35.clean/src/central_freelist.cc:262
#3  0x0000fffff7d90720 in tcmalloc::ThreadCache::FetchFromCentralCache(unsigned int, int, void* (*)(unsigned long))
    (this=0x4a22c0, cl=17, byte_size=256, oom_handler=0xfffff7d9c818 <tcmalloc::cpp_throw_oom(unsigned long)>) at ./../src/erftools-2-908ada5f35.clean/src/thread_cache.cc:126
#4  0x0000fffff7d9bb88 in tcmalloc::ThreadCache::Allocate(unsigned long, unsigned int, void* (*)(unsigned long))
    (oom_handler=0xfffff7d9c818 <tcmalloc::cpp_throw_oom(unsigned long)>, cl=17, size=256, this=0x4a22c0) at ./../src/erftools-2-908ada5f35.clean/src/thread_cache.h:380
#5  0x0000fffff7d9bb88 in malloc_fast_path<tcmalloc::cpp_throw_oom> (size=256) at ./../src/erftools-2-908ada5f35.clean/src/tcmalloc.cc:1874
#6  0x0000fffff7d9bb88 in tc_new(size_t) (size=256) at ./../src/erftools-2-908ada5f35.clean/src/tcmalloc.cc:1995

```

**Comment by ZefengWang** [comment]
the problem is the code below

``` C++
  do {
    prev = curr;
    curr = *(reinterpret_cast<void**>(curr));
  } while (++result < N && curr != NULL);
```
`curr = *(reinterpret_cast<void**>(curr));` access the invalid memory 0xff333333

**Comment by ZefengWang** [comment]
nonempty_ span has only one span block, the span's the objects addr is 0xff333333, but the addr 0xff333333 is not map to any virtual address, so when cast to void **, it access a invalid address

its tcmalloc's problem, not the application's risk. application is only called the malloc, it return the signal SIGSEGV

**Comment by ZefengWang** [comment]
> the problem is the code below
> 
> ```c++
>   do {
>     prev = curr;
>     curr = *(reinterpret_cast<void**>(curr));
>   } while (++result < N && curr != NULL);
> ```
> 
> `curr = *(reinterpret_cast<void**>(curr));` access the invalid memory 0xff333333

while N is 7, but the result is eqult to 1, it crashed

**Comment by ZefengWang** [comment]
Populate function didnt put enough memory to CentralFreeList, when allocate request, it access the invalid area on the memory

**Comment by ZefengWang** [comment]
> Please try running your program with valgrind or address sanitizer but without tcmalloc. Most likely it will help you find bug in your program.

oh， u r right, the memory has invalid writen before allocate

**Comment by alk** [comment]
Hi all. So to reiterate above, while I cannot fully rule out bug(s) in libtcmalloc, it is super-unlikely.

There are so many ways for programs to screw up with tcmalloc's (and any other malloc's) internal structures and have things crash deep inside malloc. You have double frees, you have stomping on the memory you've freed as most obvious ones, but there are more.

Yes, occasionally people will try to argue something along those lines:

* but my program works with other malloc! Well, effect of those bugs in programs will manifest differently in different malloc implementations. So it does happen from time to time, things might "work" (i.e. "not crash") in one malloc implementation, but crash with another.

* the crash is in tcmalloc guts, so it has to be your code. See above. Theoretically, could be, yes, but 99.9999% isn't.

We should do more to clarify this in our docs. In general I'd like people suspecting tcmalloc to post some reproduction programs (hopefully small). Otherwise, there is no way for me to observe you crash backtraces and conclude anything. As noted, I cannot rule out that we have no bugs. But it is super-unlikely that we have.

We also highly recommend people to test their programs with various malloc debugging tools (asan, valgrind etc).
